// Mocks generated by Mockito 5.4.1 from annotations
// in guardiannews/test/news.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:guardiannews/data/req.dart' as _i2;
import 'package:guardiannews/domain/model/news.dart' as _i5;
import 'package:guardiannews/domain/repo/news.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Requirements].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequirements extends _i1.Mock implements _i2.Requirements {
  @override
  String getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
}

/// A class which mocks [NewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepository extends _i1.Mock implements _i3.NewsRepository {
  @override
  _i4.Future<List<_i5.News>> getNews({
    int? page = 1,
    int? offset = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNews,
          [],
          {
            #page: page,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i5.News>>.value(<_i5.News>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.News>>.value(<_i5.News>[]),
      ) as _i4.Future<List<_i5.News>>);
}
