# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Android apk by tag

on:
  push:
    tags:
      - '*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      # Checkout pull request branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Java SDK
      - name: Setup Java SDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      # No need to install Dart SDK separately.
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.2"
          channel: 'stable'
          cache: true

      # Version app based on tag
      # For the build number, will use the number of commits
      - name: Version the app based on tag
        run: |
          count=`git log --oneline | wc -l | xargs`
          new_version="version: ${{ github.ref_name }}+${count}"
          sed -i -r "/version:/s/.*/$new_version/" pubspec.yaml
          cat pubspec.yaml

      # Once Flutter is installed, run pub get to fetch the app's dependencies.
      # Since Lint check is already run on pull request, this yml should be focused on building app
      - name: Install dependencies
        run: flutter pub get

      # Sometimes we might forget to run build runner and skipped missing part files
      - name: Regenerate missing part files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --set-exit-if-changed --output=none .

      # Builds apk
      - name: Build apk
        run: flutter build apk --release

      # Upload apk to release
      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: v${{ github.ref_name }}.apk
          path: build/app/outputs/flutter-apk/v${{ github.ref_name }}.apk
          overwrite: true
